import type {Metadata} from "next"
import {Quicksand, Tourney} from "next/font/google" // Stalinist_One, Michroma
import "./globals.css"
import AuthProvider from "./components/AuthProvider"

const quicksand = Quicksand({
	variable: "--font-body",
	weight: ["300", "400", "500", "600", "700"],
	subsets: ["latin"],
})

const tourney = Tourney({
	variable: "--font-heading",
	weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
	subsets: ["latin"],
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={`${quicksand.variable} ${tourney.variable} antialiased`}>
				<AuthProvider>{children}</AuthProvider>
			</body>
		</html>
	)
}
